### ISSUE TITLE
Deploying to AWS

### ISSUE THREAD

**Issue by Hobatron** [Hobatron/action-sports#66]
This one should be a solid learning experience.

**Comment by Hobatron** [comment]
I feel like I'm making good progress on this, but when I do an npm install it ALWAYS gets stuck on react-swipeable-views. I'll keep looking into it after demo day

**Comment by aemejuobi** [comment]
To deploy to AWS>

**Comment by Hobatron** [comment]
Yeah... The EC2 server has all of our code, it's just not getting past the npm install...

**Comment by aemejuobi** [comment]
So are you wanting to keep working on this and I start working on something else then?
